In [3]:
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error

In [11]:
training_X = np.array([
    [1],
    [2],
    [3],
    [4],
    [5],
    [6],
    [7],
    [8],
    [9]
])

training_y = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

validation_X = np.array([
    [10],
    [11],
    [12],
    [13],
    [14],
    [15],
    [16],
    [17],
    [18],
    [19]
])

validation_y = np.array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [12]:
r = linear_model.SGDRegressor(max_iter = 1000, 
                              learning_rate = "constant",
                              penalty = None, 
                              fit_intercept = False, 
                              eta0 = 0.01)

r.fit(training_X, training_y)

prediction_y = r.predict(validation_X)

print("Mean squared error: %.15f" % mean_squared_error(validation_y, prediction_y))
print('Linear regression accuracy: ', r.score(validation_X, validation_y))
print(prediction_y)

Mean squared error: 0.000000000000000
Linear regression accuracy:  1.0
[100. 110. 120. 130. 140. 150. 160. 170. 180. 190.]


In [13]:
class SGDRegressor:
    
    def __init__(self, max_iteration = 1000, fit_intercept = False, eta0 = 0.01):
        
        self.max_iteration = max_iteration
        self.fit_intercept = fit_intercept
        self.eta0 = eta0
        
    def fit(self, X, y):
        
        if (self.fit_intercept):
            
            X = np.insert(X, 0, 1, axis = 1)
            
            self.thetas = np.zeros(X.shape[1])
        
        else:
            
            self.thetas = np.zeros(X.shape[1])
            
        for iteration in range(self.max_iteration):
            
            for inputs, targets in zip(X, y):
                
                outputs = np.dot(self.thetas, inputs)
                
                self.thetas = self.thetas - (self.eta0 * (outputs - targets) * inputs)
                
    def predict(self, X):
        
        outputs = np.array([])
        
        if (self.fit_intercept):
            
            X = np.insert(X, 0, 1, axis = 1)
        
        for inputs in X:
            
            output = np.dot(self.thetas, inputs)
            
            outputs = np.append(outputs, [output])
        
        return outputs
    
    def score(self, X, y):
        
        predicted_y = self.predict(X)
        
        u = ((y - predicted_y) ** 2).sum() 
        v = ((y - y.mean()) ** 2).sum()
        
        return (1 - u/v)
            
        

In [14]:
r = SGDRegressor(max_iteration = 1000, fit_intercept = False, eta0 = 0.01)

r.fit(training_X, training_y)

prediction_y = r.predict(validation_X)

print("Mean squared error: %.15f" % mean_squared_error(validation_y, prediction_y))
print('Linear regression accuracy: ', r.score(validation_X, validation_y))
print(prediction_y)

Mean squared error: 0.000000000000000
Linear regression accuracy:  1.0
[100. 110. 120. 130. 140. 150. 160. 170. 180. 190.]


In [16]:
r = linear_model.LinearRegression(fit_intercept = False)

r.fit(training_X, training_y)

prediction_y = r.predict(validation_X)

print("Mean squared error: %.15f" % mean_squared_error(validation_y, prediction_y))
print('Linear regression accuracy: ', r.score(validation_X, validation_y))
print(prediction_y)

Mean squared error: 0.000000000000000
Linear regression accuracy:  1.0
[100. 110. 120. 130. 140. 150. 160. 170. 180. 190.]


In [17]:
class LinearRegression:
    
    def __init__(self, fit_intercept = True):
        
        self.fit_intercept = fit_intercept
    
    def fit(self, X, y):
        
        X_b = X
        
        if (self.fit_intercept):
            X_b = np.insert(X, 0, 1, axis = 1)
        
        self.thetas = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
    
    def predict(self, X):
        
        outputs = np.array([])
        
        if (self.fit_intercept):
            
            X = np.insert(X, 0, 1, axis = 1)
        
        for inputs in X:
            
            output = np.dot(self.thetas, inputs)
            
            outputs = np.append(outputs, [output])
        
        return outputs
        
    def score(self, X, y):
        
        predicted_y = self.predict(X)
        
        u = ((y - predicted_y) ** 2).sum() 
        v = ((y - y.mean()) ** 2).sum()
        
        return (1 - u/v)
        
        

In [18]:
r = LinearRegression(fit_intercept = False)

r.fit(training_X, training_y)

prediction_y = r.predict(validation_X)

print("Mean squared error: %.15f" % mean_squared_error(validation_y, prediction_y))
print('Linear regression accuracy: ', r.score(validation_X, validation_y))
print(prediction_y)

Mean squared error: 0.000000000000000
Linear regression accuracy:  1.0
[100. 110. 120. 130. 140. 150. 160. 170. 180. 190.]
